typography_spectrum: 0.21236310410313308
color:
  brandColors:
    - '#b0aca1'
    - '#1a181b'
    - '#4b5054'
    - '#c05833'
    - '#ffe3d0'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.96326
analytics:
  google: null
  facebook: null
  twitter: null
name: ClimbingBlake
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: RRGCC.org
    url: 'http://rrgcc.org'
    type: external
favicon: null
title: Climbing & Coding
purpose: []
