name: ClimbingBlake
favicon: null
layout_spectrum: 0.6210215918254107
typography_spectrum: 0.21236310410313308
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9597674773540348
  lightness: 0.5776203265413642
  saturation: 0.5038472276646644
  rhythmicContrast: 0.48813149239867926
purpose: []
