layout_spectrum: 0.5234796535223722
typography_spectrum: 0.3013858285266906
color:
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  brandStrength: 0.9594805417582393
  lightness: 0.3748987284488976
  saturation: 0.5881582431029528
  rhythmicContrast: 0.4480811676476151
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: ClimbingBlake
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: RRGCC.org
    url: 'http://rrgcc.org'
    type: external
favicon: null
title: Climbing & Coding
purpose: []
